# -*- coding: utf-8 -*-
"""All the Intermediate Colleges in Pakistan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqO-8PgaxG5294SBpA-5WArv-3x-NC_A
"""

import pandas as pd

file_path = '/content/All the Intermediate Colleges in Pakistan.csv'

data = pd.read_csv(file_path)

data.head()

missing_values = data.isnull().sum()

data['Sector'] = data['Sector'].str.capitalize()

data['Affiliation'] = data['Affiliation'].str.upper()

missing_values

data['Location'].fillna('Unknown', inplace=True)

data['Sector'].fillna('Unknown', inplace=True)

data['Affiliation'].fillna('Unknown', inplace=True)

summary_statistics = data.describe(include='all')

summary_statistics

import matplotlib.pyplot as plt

import seaborn as sns

sns.set(style="whitegrid")

plt.figure(figsize=(10, 6))

sns.countplot(data=data, x='Sector', palette='viridis')

plt.title('Distribution of Colleges by Sector')

plt.xlabel('Sector')

plt.ylabel('Count')

plt.show()

plt.figure(figsize=(12, 6))

sns.countplot(data=data, x='Rating', order=data['Rating'].value_counts().index, palette='viridis')

plt.title('Distribution of College Ratings')

plt.xlabel('Rating')

plt.ylabel('Count')

plt.xticks(rotation=90)

plt.show()